import barImg from "@/assets/bar.jpg";
import coinsImg from "@/assets/coins.jpg";
import silverImg from "@/assets/silver.jpg";
import jewelryImg from "@/assets/jewelry.jpg";

import { lang } from "./i18n";
import type { GramPrices } from "./prices.server";

export const navLinks = [
  { label: "الرئيسية", to: "/" },
  { label: "مجموعتنا", to: "/collection" },
  { label: "الفضة", to: "/silver" },
  { label: "سعر الذهب", to: "/gold-price" },
  { label: "سعر الفضة", to: "/silver-price" },
  { label: "حاسبة الميزانية", to: "/budget-calculator" },
  { label: "حساب الزكاة", to: "/zakat" },
  { label: "الأخبار", to: "/news" },
  { label: "فروعنا", to: "/branches" },
] as const;

/** روابط "مركز المساعدة" في الفوتر. */
export const helpLinks = [
  { label: "من نحن", to: "/about" },
  { label: "إتصل بنا", to: "/contact" },
  { label: "الأسئلة الشائعة", to: "/faq" },
  { label: "طرق الدفع", to: "/payment-methods" },
  { label: "الشروط والأحكام", to: "/terms" },
  { label: "سياسة الخصوصية", to: "/privacy" },
  { label: "سياسة الشحن والتوصيل", to: "/shipping-policy" },
  { label: "سياسة الاسترجاع واسترداد الأموال", to: "/refund-policy" },
] as const;

export type Metal = "gold" | "silver";
export type Karat = 24 | 22 | 21 | 18;

export const CATEGORIES = ["سبائك ذهب", "عملات ذهبية", "مشغولات", "سبائك فضة"] as const;
export type Category = (typeof CATEGORIES)[number];

export const PROVIDERS = ["أورا", "سام", "بي تي سي", "جولد إيرا"] as const;
export type Provider = (typeof PROVIDERS)[number];

export type Product = {
  slug: string;
  img: string;
  /** الاسم */
  t: string;
  /** السطر الفرعي */
  s: string;
  metal: Metal;
  cat: Category;
  weightG: number;
  /** العيار — فارغ لمنتجات الفضة */
  karat: Karat | null;
  purity: string;
  /** العلامة التجارية / المورّد */
  provider: Provider;
  /** نسبة المصنعية فوق قيمة المعدن */
  fabrication: number;
  /** نسبة المصنعية المستردّة عند إعادة البيع (الكاش باك) */
  cashbackPct: number;
  available: boolean;
  desc: string;
};

/** مفتاح سعر الجرام المقابل للمنتج. */
export const gramKeyOf = (p: Product): keyof GramPrices =>
  p.metal === "silver" ? "silver" : (`k${p.karat ?? 24}` as keyof GramPrices);

/** سعر شراء المنتج = قيمة المعدن + المصنعية. */
export const buyPrice = (p: Product, gram?: GramPrices): number | undefined =>
  gram && gram[gramKeyOf(p)] * p.weightG * (1 + p.fabrication);

/** سعر إعادة البيع = قيمة المعدن بسعر البيع + الجزء المستردّ من المصنعية. */
export const sellPrice = (p: Product, sell?: GramPrices): number | undefined =>
  sell && sell[gramKeyOf(p)] * p.weightG * (1 + p.fabrication * p.cashbackPct);

// ponytail: يقرأ اللغة من حالة عامة بدل hook لأنه يُستدعى من دوال خالصة؛ حوّله لـ hook لو احتجت تعدد لغات متزامن.
export const weightLabel = (g: number) =>
  g >= 1000
    ? `${g / 1000} ${lang() === "en" ? "kg" : "كيلو"}`
    : `${g} ${lang() === "en" ? "g" : "جرام"}`;

export const allProducts: Product[] = [
  {
    slug: "gold-bar-0-25g",
    img: barImg,
    t: "سبيكة ذهب 0.25 جرام",
    s: "عيار 24 – 999.9",
    metal: "gold",
    cat: "سبائك ذهب",
    weightG: 0.25,
    karat: 24,
    purity: "999.9",
    provider: "أورا",
    fabrication: 0.12,
    cashbackPct: 0.5,
    available: true,
    desc: "سبيكة ذهب خالص عيار 24 بوزن 0.25 جرام من أورا، مختومة من مصلحة الدمغة والموازين ومغلّفة في عبوة مؤمّنة ضد العبث. السعر مرتبط بسعر الذهب اللحظي في السوق المصري، ويمكنك استرداد حتى 50% من المصنعية عند إعادة البيع بشرط بقاء العبوة الأصلية.",
  },
  {
    slug: "gold-bar-0-5g",
    img: barImg,
    t: "سبيكة ذهب 0.5 جرام",
    s: "عيار 24 – 999.9",
    metal: "gold",
    cat: "سبائك ذهب",
    weightG: 0.5,
    karat: 24,
    purity: "999.9",
    provider: "أورا",
    fabrication: 0.1,
    cashbackPct: 0.5,
    available: true,
    desc: "سبيكة ذهب خالص عيار 24 بوزن 0.5 جرام من أورا، مختومة من مصلحة الدمغة والموازين ومغلّفة في عبوة مؤمّنة ضد العبث. السعر مرتبط بسعر الذهب اللحظي في السوق المصري، ويمكنك استرداد حتى 50% من المصنعية عند إعادة البيع بشرط بقاء العبوة الأصلية.",
  },
  {
    slug: "gold-bar-1g",
    img: barImg,
    t: "سبيكة ذهب 1 جرام",
    s: "عيار 24 – 999.9",
    metal: "gold",
    cat: "سبائك ذهب",
    weightG: 1,
    karat: 24,
    purity: "999.9",
    provider: "سام",
    fabrication: 0.08,
    cashbackPct: 0.5,
    available: true,
    desc: "سبيكة ذهب خالص عيار 24 بوزن 1 جرام من سام، مختومة من مصلحة الدمغة والموازين ومغلّفة في عبوة مؤمّنة ضد العبث. السعر مرتبط بسعر الذهب اللحظي في السوق المصري، ويمكنك استرداد حتى 50% من المصنعية عند إعادة البيع بشرط بقاء العبوة الأصلية.",
  },
  {
    slug: "gold-bar-2-5g",
    img: barImg,
    t: "سبيكة ذهب 2.5 جرام",
    s: "عيار 24 – 999.9",
    metal: "gold",
    cat: "سبائك ذهب",
    weightG: 2.5,
    karat: 24,
    purity: "999.9",
    provider: "سام",
    fabrication: 0.06,
    cashbackPct: 0.5,
    available: true,
    desc: "سبيكة ذهب خالص عيار 24 بوزن 2.5 جرام من سام، مختومة من مصلحة الدمغة والموازين ومغلّفة في عبوة مؤمّنة ضد العبث. السعر مرتبط بسعر الذهب اللحظي في السوق المصري، ويمكنك استرداد حتى 50% من المصنعية عند إعادة البيع بشرط بقاء العبوة الأصلية.",
  },
  {
    slug: "gold-bar-5g",
    img: barImg,
    t: "سبيكة ذهب 5 جرام",
    s: "عيار 24 – 999.9",
    metal: "gold",
    cat: "سبائك ذهب",
    weightG: 5,
    karat: 24,
    purity: "999.9",
    provider: "سام",
    fabrication: 0.045,
    cashbackPct: 0.5,
    available: true,
    desc: "سبيكة ذهب خالص عيار 24 بوزن 5 جرام من سام، مختومة من مصلحة الدمغة والموازين ومغلّفة في عبوة مؤمّنة ضد العبث. السعر مرتبط بسعر الذهب اللحظي في السوق المصري، ويمكنك استرداد حتى 50% من المصنعية عند إعادة البيع بشرط بقاء العبوة الأصلية.",
  },
  {
    slug: "gold-bar-10g",
    img: barImg,
    t: "سبيكة ذهب 10 جرام",
    s: "عيار 24 – 999.9",
    metal: "gold",
    cat: "سبائك ذهب",
    weightG: 10,
    karat: 24,
    purity: "999.9",
    provider: "سام",
    fabrication: 0.03,
    cashbackPct: 0.5,
    available: true,
    desc: "سبيكة ذهب خالص عيار 24 بوزن 10 جرام من سام، مختومة من مصلحة الدمغة والموازين ومغلّفة في عبوة مؤمّنة ضد العبث. السعر مرتبط بسعر الذهب اللحظي في السوق المصري، ويمكنك استرداد حتى 50% من المصنعية عند إعادة البيع بشرط بقاء العبوة الأصلية.",
  },
  {
    slug: "gold-bar-20g",
    img: barImg,
    t: "سبيكة ذهب 20 جرام",
    s: "عيار 24 – 999.9",
    metal: "gold",
    cat: "سبائك ذهب",
    weightG: 20,
    karat: 24,
    purity: "999.9",
    provider: "سام",
    fabrication: 0.025,
    cashbackPct: 0.5,
    available: true,
    desc: "سبيكة ذهب خالص عيار 24 بوزن 20 جرام من سام، مختومة من مصلحة الدمغة والموازين ومغلّفة في عبوة مؤمّنة ضد العبث. السعر مرتبط بسعر الذهب اللحظي في السوق المصري، ويمكنك استرداد حتى 50% من المصنعية عند إعادة البيع بشرط بقاء العبوة الأصلية.",
  },
  {
    slug: "gold-bar-31-1g",
    img: barImg,
    t: "سبيكة ذهب 31.1 جرام",
    s: "عيار 24 – 999.9",
    metal: "gold",
    cat: "سبائك ذهب",
    weightG: 31.1,
    karat: 24,
    purity: "999.9",
    provider: "بي تي سي",
    fabrication: 0.022,
    cashbackPct: 0.5,
    available: true,
    desc: "سبيكة ذهب خالص عيار 24 بوزن 31.1 جرام من بي تي سي، مختومة من مصلحة الدمغة والموازين ومغلّفة في عبوة مؤمّنة ضد العبث. السعر مرتبط بسعر الذهب اللحظي في السوق المصري، ويمكنك استرداد حتى 50% من المصنعية عند إعادة البيع بشرط بقاء العبوة الأصلية.",
  },
  {
    slug: "gold-bar-50g",
    img: barImg,
    t: "سبيكة ذهب 50 جرام",
    s: "عيار 24 – 999.9",
    metal: "gold",
    cat: "سبائك ذهب",
    weightG: 50,
    karat: 24,
    purity: "999.9",
    provider: "بي تي سي",
    fabrication: 0.02,
    cashbackPct: 0.5,
    available: true,
    desc: "سبيكة ذهب خالص عيار 24 بوزن 50 جرام من بي تي سي، مختومة من مصلحة الدمغة والموازين ومغلّفة في عبوة مؤمّنة ضد العبث. السعر مرتبط بسعر الذهب اللحظي في السوق المصري، ويمكنك استرداد حتى 50% من المصنعية عند إعادة البيع بشرط بقاء العبوة الأصلية.",
  },
  {
    slug: "gold-bar-100g",
    img: barImg,
    t: "سبيكة ذهب 100 جرام",
    s: "عيار 24 – 999.9",
    metal: "gold",
    cat: "سبائك ذهب",
    weightG: 100,
    karat: 24,
    purity: "999.9",
    provider: "جولد إيرا",
    fabrication: 0.018,
    cashbackPct: 0.5,
    available: false,
    desc: "سبيكة ذهب خالص عيار 24 بوزن 100 جرام من جولد إيرا، مختومة من مصلحة الدمغة والموازين ومغلّفة في عبوة مؤمّنة ضد العبث. السعر مرتبط بسعر الذهب اللحظي في السوق المصري، ويمكنك استرداد حتى 50% من المصنعية عند إعادة البيع بشرط بقاء العبوة الأصلية.",
  },
  {
    slug: "gold-sovereign-coin",
    img: coinsImg,
    t: "جنيه ذهب إنجليزي",
    s: "عيار 22 – 8 جرام",
    metal: "gold",
    cat: "عملات ذهبية",
    weightG: 8,
    karat: 22,
    purity: "916.7",
    provider: "أورا",
    fabrication: 0.06,
    cashbackPct: 0.3,
    available: true,
    desc: "جنيه ذهب إنجليزي عيار 22 بوزن 8 جرام، من أكثر العملات الذهبية تداولًا في السوق المصري وأسرعها في إعادة البيع. مرفق معها شهادة أصل وعبوة محكمة الغلق.",
  },
  {
    slug: "gold-half-sovereign",
    img: coinsImg,
    t: "نصف جنيه ذهب",
    s: "عيار 22 – 4 جرام",
    metal: "gold",
    cat: "عملات ذهبية",
    weightG: 4,
    karat: 22,
    purity: "916.7",
    provider: "أورا",
    fabrication: 0.07,
    cashbackPct: 0.3,
    available: true,
    desc: "نصف جنيه ذهب عيار 22 بوزن 4 جرام، من أكثر العملات الذهبية تداولًا في السوق المصري وأسرعها في إعادة البيع. مرفق معها شهادة أصل وعبوة محكمة الغلق.",
  },
  {
    slug: "ora-gold-coin",
    img: coinsImg,
    t: "عملة ذهب أورا",
    s: "عيار 24 – 8 جرام",
    metal: "gold",
    cat: "عملات ذهبية",
    weightG: 8,
    karat: 24,
    purity: "999.9",
    provider: "أورا",
    fabrication: 0.06,
    cashbackPct: 0.5,
    available: true,
    desc: "عملة ذهب أورا عيار 24 بوزن 8 جرام، من أكثر العملات الذهبية تداولًا في السوق المصري وأسرعها في إعادة البيع. مرفق معها شهادة أصل وعبوة محكمة الغلق.",
  },
  {
    slug: "ora-gold-coin-4g",
    img: coinsImg,
    t: "عملة ذهب أورا 4 جرام",
    s: "عيار 24 – 4 جرام",
    metal: "gold",
    cat: "عملات ذهبية",
    weightG: 4,
    karat: 24,
    purity: "999.9",
    provider: "أورا",
    fabrication: 0.07,
    cashbackPct: 0.5,
    available: true,
    desc: "عملة ذهب أورا 4 جرام عيار 24 بوزن 4 جرام، من أكثر العملات الذهبية تداولًا في السوق المصري وأسرعها في إعادة البيع. مرفق معها شهادة أصل وعبوة محكمة الغلق.",
  },
  {
    slug: "classic-gold-set",
    img: jewelryImg,
    t: "طقم ذهب كلاسيك",
    s: "عيار 21 – 12 جرام",
    metal: "gold",
    cat: "مشغولات",
    weightG: 12,
    karat: 21,
    purity: "875",
    provider: "أورا",
    fabrication: 0.09,
    cashbackPct: 0.0,
    available: true,
    desc: "طقم ذهب كلاسيك عيار 21 بوزن 12 جرام، مدموغ بمصلحة الدمغة والموازين ومرفق معه فاتورة ضريبية معتمدة وشهادة ضمان.",
  },
  {
    slug: "egyptian-gold-bangle",
    img: jewelryImg,
    t: "غويشة ذهب مصرية",
    s: "عيار 21 – 12 جرام",
    metal: "gold",
    cat: "مشغولات",
    weightG: 12,
    karat: 21,
    purity: "875",
    provider: "أورا",
    fabrication: 0.09,
    cashbackPct: 0.0,
    available: true,
    desc: "غويشة ذهب مصرية عيار 21 بوزن 12 جرام، مدموغ بمصلحة الدمغة والموازين ومرفق معه فاتورة ضريبية معتمدة وشهادة ضمان.",
  },
  {
    slug: "gold-chain-18k",
    img: jewelryImg,
    t: "سلسلة ذهب عيار 18",
    s: "عيار 18 – 6 جرام",
    metal: "gold",
    cat: "مشغولات",
    weightG: 6,
    karat: 18,
    purity: "750",
    provider: "أورا",
    fabrication: 0.1,
    cashbackPct: 0.0,
    available: false,
    desc: "سلسلة ذهب عيار 18 عيار 18 بوزن 6 جرام، مدموغ بمصلحة الدمغة والموازين ومرفق معه فاتورة ضريبية معتمدة وشهادة ضمان.",
  },
  {
    slug: "silver-bar-5g",
    img: silverImg,
    t: "سبيكة فضة 5 جرام",
    s: "فضة 999",
    metal: "silver",
    cat: "سبائك فضة",
    weightG: 5,
    karat: null,
    purity: "999",
    provider: "بي تي سي",
    fabrication: 0.15,
    cashbackPct: 0.3,
    available: true,
    desc: "سبيكة فضة نقية 999 بوزن 5 جرام من بي تي سي، مغلّفة في عبوة مؤمّنة. بديل اقتصادي لبدء الادخار في المعادن النفيسة وتنويع المحفظة.",
  },
  {
    slug: "silver-bar-8g",
    img: silverImg,
    t: "سبيكة فضة 8 جرام",
    s: "فضة 999",
    metal: "silver",
    cat: "سبائك فضة",
    weightG: 8,
    karat: null,
    purity: "999",
    provider: "بي تي سي",
    fabrication: 0.14,
    cashbackPct: 0.3,
    available: true,
    desc: "سبيكة فضة نقية 999 بوزن 8 جرام من بي تي سي، مغلّفة في عبوة مؤمّنة. بديل اقتصادي لبدء الادخار في المعادن النفيسة وتنويع المحفظة.",
  },
  {
    slug: "silver-bar-10g",
    img: silverImg,
    t: "سبيكة فضة 10 جرام",
    s: "فضة 999",
    metal: "silver",
    cat: "سبائك فضة",
    weightG: 10,
    karat: null,
    purity: "999",
    provider: "بي تي سي",
    fabrication: 0.12,
    cashbackPct: 0.3,
    available: true,
    desc: "سبيكة فضة نقية 999 بوزن 10 جرام من بي تي سي، مغلّفة في عبوة مؤمّنة. بديل اقتصادي لبدء الادخار في المعادن النفيسة وتنويع المحفظة.",
  },
  {
    slug: "silver-bar-50g",
    img: silverImg,
    t: "سبيكة فضة 50 جرام",
    s: "فضة 999",
    metal: "silver",
    cat: "سبائك فضة",
    weightG: 50,
    karat: null,
    purity: "999",
    provider: "بي تي سي",
    fabrication: 0.08,
    cashbackPct: 0.3,
    available: true,
    desc: "سبيكة فضة نقية 999 بوزن 50 جرام من بي تي سي، مغلّفة في عبوة مؤمّنة. بديل اقتصادي لبدء الادخار في المعادن النفيسة وتنويع المحفظة.",
  },
  {
    slug: "silver-bar-100g",
    img: silverImg,
    t: "سبيكة فضة 100 جرام",
    s: "فضة 999",
    metal: "silver",
    cat: "سبائك فضة",
    weightG: 100,
    karat: null,
    purity: "999",
    provider: "بي تي سي",
    fabrication: 0.06,
    cashbackPct: 0.3,
    available: true,
    desc: "سبيكة فضة نقية 999 بوزن 100 جرام من بي تي سي، مغلّفة في عبوة مؤمّنة. بديل اقتصادي لبدء الادخار في المعادن النفيسة وتنويع المحفظة.",
  },
  {
    slug: "silver-bar-250g",
    img: silverImg,
    t: "سبيكة فضة 250 جرام",
    s: "فضة 999",
    metal: "silver",
    cat: "سبائك فضة",
    weightG: 250,
    karat: null,
    purity: "999",
    provider: "جولد إيرا",
    fabrication: 0.05,
    cashbackPct: 0.3,
    available: true,
    desc: "سبيكة فضة نقية 999 بوزن 250 جرام من جولد إيرا، مغلّفة في عبوة مؤمّنة. بديل اقتصادي لبدء الادخار في المعادن النفيسة وتنويع المحفظة.",
  },
  {
    slug: "silver-bar-500g",
    img: silverImg,
    t: "سبيكة فضة 500 جرام",
    s: "فضة 999",
    metal: "silver",
    cat: "سبائك فضة",
    weightG: 500,
    karat: null,
    purity: "999",
    provider: "جولد إيرا",
    fabrication: 0.045,
    cashbackPct: 0.3,
    available: true,
    desc: "سبيكة فضة نقية 999 بوزن 500 جرام من جولد إيرا، مغلّفة في عبوة مؤمّنة. بديل اقتصادي لبدء الادخار في المعادن النفيسة وتنويع المحفظة.",
  },
  {
    slug: "silver-bar-1000g",
    img: silverImg,
    t: "سبيكة فضة 1 كيلو",
    s: "فضة 999",
    metal: "silver",
    cat: "سبائك فضة",
    weightG: 1000,
    karat: null,
    purity: "999",
    provider: "جولد إيرا",
    fabrication: 0.04,
    cashbackPct: 0.3,
    available: false,
    desc: "سبيكة فضة نقية 999 بوزن 1 كيلو من جولد إيرا، مغلّفة في عبوة مؤمّنة. بديل اقتصادي لبدء الادخار في المعادن النفيسة وتنويع المحفظة.",
  },
];

export const productBySlug = (slug: string) => allProducts.find((p) => p.slug === slug);

export const GOVERNORATES = [
  "القاهرة",
  "الجيزة",
  "الإسكندرية",
  "القليوبية",
  "الدقهلية",
  "الشرقية",
  "الغربية",
  "المنوفية",
  "البحيرة",
  "كفر الشيخ",
  "دمياط",
  "بورسعيد",
  "الإسماعيلية",
  "السويس",
  "شمال سيناء",
  "جنوب سيناء",
  "بني سويف",
  "الفيوم",
  "المنيا",
  "أسيوط",
  "سوهاج",
  "قنا",
  "الأقصر",
  "أسوان",
  "البحر الأحمر",
  "الوادي الجديد",
  "مطروح",
] as const;
export const branches = [
  {
    city: "الإسكندرية",
    name: "فرع سموحة",
    address: "14 شارع فيكتور عمانويل، سموحة، الإسكندرية",
    phone: "17608",
    hours: "يوميًا 10 ص – 10 م",
  },
  {
    city: "القاهرة",
    name: "فرع مدينة نصر",
    address: "22 شارع عباس العقاد، مدينة نصر، القاهرة",
    phone: "17608",
    hours: "يوميًا 10 ص – 11 م",
  },
  {
    city: "الجيزة",
    name: "فرع المهندسين",
    address: "8 شارع جامعة الدول العربية، المهندسين، الجيزة",
    phone: "17608",
    hours: "يوميًا 11 ص – 10 م",
  },
  {
    city: "المنصورة",
    name: "فرع المنصورة",
    address: "5 شارع الجمهورية، المنصورة، الدقهلية",
    phone: "17608",
    hours: "السبت – الخميس 10 ص – 9 م",
  },
];
