/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as GoldPriceRouteImport } from './routes/gold-price'
import { Route as NewsRouteImport } from './routes/news'
import { Route as SilverRouteImport } from './routes/silver'
import { Route as ZakatRouteImport } from './routes/zakat'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ApiPublicPricesStreamRouteImport } from './routes/api/public/prices-stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldPriceRoute = GoldPriceRouteImport.update({
  id: '/gold-price',
  path: '/gold-price',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const SilverRoute = SilverRouteImport.update({
  id: '/silver',
  path: '/silver',
  getParentRoute: () => rootRouteImport,
} as any)
const ZakatRoute = ZakatRouteImport.update({
  id: '/zakat',
  path: '/zakat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPricesStreamRoute = ApiPublicPricesStreamRouteImport.update({
  id: '/api/public/prices-stream',
  path: '/api/public/prices-stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/branches': typeof BranchesRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collection': typeof CollectionRoute
  '/gold-price': typeof GoldPriceRoute
  '/news': typeof NewsRoute
  '/silver': typeof SilverRoute
  '/zakat': typeof ZakatRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public/prices-stream': typeof ApiPublicPricesStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/branches': typeof BranchesRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collection': typeof CollectionRoute
  '/gold-price': typeof GoldPriceRoute
  '/news': typeof NewsRoute
  '/silver': typeof SilverRoute
  '/zakat': typeof ZakatRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public/prices-stream': typeof ApiPublicPricesStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/branches': typeof BranchesRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collection': typeof CollectionRoute
  '/gold-price': typeof GoldPriceRoute
  '/news': typeof NewsRoute
  '/silver': typeof SilverRoute
  '/zakat': typeof ZakatRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public/prices-stream': typeof ApiPublicPricesStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/branches'
    | '/cart'
    | '/checkout'
    | '/collection'
    | '/gold-price'
    | '/news'
    | '/silver'
    | '/zakat'
    | '/products/$slug'
    | '/api/public/prices-stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/branches'
    | '/cart'
    | '/checkout'
    | '/collection'
    | '/gold-price'
    | '/news'
    | '/silver'
    | '/zakat'
    | '/products/$slug'
    | '/api/public/prices-stream'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/branches'
    | '/cart'
    | '/checkout'
    | '/collection'
    | '/gold-price'
    | '/news'
    | '/silver'
    | '/zakat'
    | '/products/$slug'
    | '/api/public/prices-stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  BranchesRoute: typeof BranchesRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CollectionRoute: typeof CollectionRoute
  GoldPriceRoute: typeof GoldPriceRoute
  NewsRoute: typeof NewsRoute
  SilverRoute: typeof SilverRoute
  ZakatRoute: typeof ZakatRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ApiPublicPricesStreamRoute: typeof ApiPublicPricesStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-price': {
      id: '/gold-price'
      path: '/gold-price'
      fullPath: '/gold-price'
      preLoaderRoute: typeof GoldPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/silver': {
      id: '/silver'
      path: '/silver'
      fullPath: '/silver'
      preLoaderRoute: typeof SilverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zakat': {
      id: '/zakat'
      path: '/zakat'
      fullPath: '/zakat'
      preLoaderRoute: typeof ZakatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/prices-stream': {
      id: '/api/public/prices-stream'
      path: '/api/public/prices-stream'
      fullPath: '/api/public/prices-stream'
      preLoaderRoute: typeof ApiPublicPricesStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  BranchesRoute: BranchesRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CollectionRoute: CollectionRoute,
  GoldPriceRoute: GoldPriceRoute,
  NewsRoute: NewsRoute,
  SilverRoute: SilverRoute,
  ZakatRoute: ZakatRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ApiPublicPricesStreamRoute: ApiPublicPricesStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
