/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as BudgetCalculatorRouteImport } from './routes/budget-calculator'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GoldPriceRouteImport } from './routes/gold-price'
import { Route as NewsRouteImport } from './routes/news'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PaymentMethodsRouteImport } from './routes/payment-methods'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as SilverRouteImport } from './routes/silver'
import { Route as SilverPriceRouteImport } from './routes/silver-price'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ZakatRouteImport } from './routes/zakat'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ApiPublicPricesStreamRouteImport } from './routes/api/public/prices-stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetCalculatorRoute = BudgetCalculatorRouteImport.update({
  id: '/budget-calculator',
  path: '/budget-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldPriceRoute = GoldPriceRouteImport.update({
  id: '/gold-price',
  path: '/gold-price',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentMethodsRoute = PaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SilverRoute = SilverRouteImport.update({
  id: '/silver',
  path: '/silver',
  getParentRoute: () => rootRouteImport,
} as any)
const SilverPriceRoute = SilverPriceRouteImport.update({
  id: '/silver-price',
  path: '/silver-price',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ZakatRoute = ZakatRouteImport.update({
  id: '/zakat',
  path: '/zakat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPricesStreamRoute = ApiPublicPricesStreamRouteImport.update({
  id: '/api/public/prices-stream',
  path: '/api/public/prices-stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/branches': typeof BranchesRoute
  '/budget-calculator': typeof BudgetCalculatorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gold-price': typeof GoldPriceRoute
  '/news': typeof NewsRoute
  '/orders': typeof OrdersRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/silver': typeof SilverRoute
  '/silver-price': typeof SilverPriceRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/zakat': typeof ZakatRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public/prices-stream': typeof ApiPublicPricesStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/branches': typeof BranchesRoute
  '/budget-calculator': typeof BudgetCalculatorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gold-price': typeof GoldPriceRoute
  '/news': typeof NewsRoute
  '/orders': typeof OrdersRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/silver': typeof SilverRoute
  '/silver-price': typeof SilverPriceRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/zakat': typeof ZakatRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public/prices-stream': typeof ApiPublicPricesStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/branches': typeof BranchesRoute
  '/budget-calculator': typeof BudgetCalculatorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gold-price': typeof GoldPriceRoute
  '/news': typeof NewsRoute
  '/orders': typeof OrdersRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/silver': typeof SilverRoute
  '/silver-price': typeof SilverPriceRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/zakat': typeof ZakatRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public/prices-stream': typeof ApiPublicPricesStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/branches'
    | '/budget-calculator'
    | '/cart'
    | '/checkout'
    | '/collection'
    | '/contact'
    | '/faq'
    | '/gold-price'
    | '/news'
    | '/orders'
    | '/payment-methods'
    | '/privacy'
    | '/refund-policy'
    | '/shipping-policy'
    | '/silver'
    | '/silver-price'
    | '/terms'
    | '/wallet'
    | '/zakat'
    | '/products/$slug'
    | '/api/public/prices-stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/branches'
    | '/budget-calculator'
    | '/cart'
    | '/checkout'
    | '/collection'
    | '/contact'
    | '/faq'
    | '/gold-price'
    | '/news'
    | '/orders'
    | '/payment-methods'
    | '/privacy'
    | '/refund-policy'
    | '/shipping-policy'
    | '/silver'
    | '/silver-price'
    | '/terms'
    | '/wallet'
    | '/zakat'
    | '/products/$slug'
    | '/api/public/prices-stream'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/branches'
    | '/budget-calculator'
    | '/cart'
    | '/checkout'
    | '/collection'
    | '/contact'
    | '/faq'
    | '/gold-price'
    | '/news'
    | '/orders'
    | '/payment-methods'
    | '/privacy'
    | '/refund-policy'
    | '/shipping-policy'
    | '/silver'
    | '/silver-price'
    | '/terms'
    | '/wallet'
    | '/zakat'
    | '/products/$slug'
    | '/api/public/prices-stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  BranchesRoute: typeof BranchesRoute
  BudgetCalculatorRoute: typeof BudgetCalculatorRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CollectionRoute: typeof CollectionRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GoldPriceRoute: typeof GoldPriceRoute
  NewsRoute: typeof NewsRoute
  OrdersRoute: typeof OrdersRoute
  PaymentMethodsRoute: typeof PaymentMethodsRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  SilverRoute: typeof SilverRoute
  SilverPriceRoute: typeof SilverPriceRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRoute
  ZakatRoute: typeof ZakatRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ApiPublicPricesStreamRoute: typeof ApiPublicPricesStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget-calculator': {
      id: '/budget-calculator'
      path: '/budget-calculator'
      fullPath: '/budget-calculator'
      preLoaderRoute: typeof BudgetCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-price': {
      id: '/gold-price'
      path: '/gold-price'
      fullPath: '/gold-price'
      preLoaderRoute: typeof GoldPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-methods': {
      id: '/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof PaymentMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/silver': {
      id: '/silver'
      path: '/silver'
      fullPath: '/silver'
      preLoaderRoute: typeof SilverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/silver-price': {
      id: '/silver-price'
      path: '/silver-price'
      fullPath: '/silver-price'
      preLoaderRoute: typeof SilverPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zakat': {
      id: '/zakat'
      path: '/zakat'
      fullPath: '/zakat'
      preLoaderRoute: typeof ZakatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/prices-stream': {
      id: '/api/public/prices-stream'
      path: '/api/public/prices-stream'
      fullPath: '/api/public/prices-stream'
      preLoaderRoute: typeof ApiPublicPricesStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  BranchesRoute: BranchesRoute,
  BudgetCalculatorRoute: BudgetCalculatorRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CollectionRoute: CollectionRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GoldPriceRoute: GoldPriceRoute,
  NewsRoute: NewsRoute,
  OrdersRoute: OrdersRoute,
  PaymentMethodsRoute: PaymentMethodsRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  SilverRoute: SilverRoute,
  SilverPriceRoute: SilverPriceRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRoute,
  ZakatRoute: ZakatRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ApiPublicPricesStreamRoute: ApiPublicPricesStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
